version: '2'
services:
  {{cookiecutter.repo_name}}:
    restart: always
    build: .
    image: luismayta/ubuntu-dotfiles:latest
    volumes_from:
      - source_store

  # Volumes source
  source_store:
    image: busybox
    volumes:
      - ./:/app/
